### ISSUE TITLE
reaching the end of line in a comment creates inconsistent behaviour in the output

### ISSUE THREAD

**Issue by hoheinzollern** [affeldt-aist/coq2html#32] opened 2024-03-20 12:26 UTC
See for example this output:

![image](https://github.com/affeldt-aist/coq2html/assets/253462/3c5186cc-b7e6-4cdd-a288-6e2f0b562aa3)

The behavior should be consistent, if the headers stick to, e.g., an 80 column limit, then you might have some line ending on `last words *)` and another line ending in `last words    *)`, producing two different line break behaviors.

**Comment by yoshihiro503** [comment] 2024-03-22 07:15
Depending on the markdown specification, two or one space at the end of a line may or may not result in a line break. It seems a bit strange to distort markdown's behavior to conform to the convention of writing comments with an 80-character limit. However, it may be inconvenient for previous users that the difference between ` *)` and `  *)` significantly changes the appearance of the html.
I have prepared an execution flag `-fragile-mathcomp-break` for light users who prefer to see things as they are written: https://github.com/affeldt-aist/coq2html/pull/37

**Comment by affeldt-aist** [comment] 2024-03-26 06:32
#37 has been merged, @hoheinzollern do you think it solves the issue?

**Comment by proux01** [comment] 2024-04-17 07:43
This is a duplicate of #17 (and I think it could be closed as such), not solved by #37 (c.f. https://github.com/affeldt-aist/coq2html/issues/17#issuecomment-2019934034 )

**Closed** 2024-09-27 07:05 UTC
